import os
import json
from groq import Groq
import spotipy
from spotipy.oauth2 import SpotifyOAuth

# 1. Initialize Clients
groq_client = Groq()
sp = spotipy.Spotify(auth_manager=SpotifyOAuth(
    scope="playlist-modify-public",
    client_id=os.getenv("SPOTIPY_CLIENT_ID"),
    client_secret=os.getenv("SPOTIPY_CLIENT_SECRET"),
    redirect_uri=os.getenv("SPOTIPY_REDIRECT_URI")
))

# 2. Get User Input
user_prompt = "Make a high energy songs playlist with songs from charli xcx and kim petras"
print(f"🤖 Processing your request: '{user_prompt}'...")

# 3. Step 1: Query Groq AI for Structured Song Data
ai_response = groq_client.chat.completions.create(
    model="llama-3.1-8b-instant",
    messages=[
        {
            "role": "system",
            "content": (
                "You are an expert music curator and data extractor. "
                "If the user provides a list of songs, extract them. "
                "If the user asks for a theme, generate a list of 5-10 real, popular tracks. "
                "You must respond ONLY with a valid JSON array of objects. "
                "Each object must have 'artist' and 'track' keys. "
                "Do not include intro text, markdown code blocks, or explanations."
            )
        },
        {
            "role": "user",
            "content": user_prompt
        }
    ]
)

# Extract and load the JSON output
raw_output = ai_response.choices[0].message.content.strip()
try:
    songs_to_find = json.loads(raw_output)
except json.JSONDecodeError:
    print("❌ Failed to parse AI JSON response.")
    exit()

# 4. Step 2: Search Spotify for IDs
print("\n🔍 Searching Spotify for tracks...")
track_uris = []
for song in songs_to_find:
    query = f"artist:{song['artist']} track:{song['track']}"
    results = sp.search(q=query, type="track", limit=1)
    items = results.get("tracks", {}).get("items", [])
    
    if items:
        uri = items[0]["uri"]
        print(f" ✅ Found: {song['artist']} - {song['track']}")
        track_uris.append(uri)
    else:
        print(f" ❌ Missing: {song['artist']} - {song['track']}")

# 5. Step 3: Create the Playlist and Add Songs
if track_uris:
    print("\n🎵 Creating your Spotify playlist...")
    user_id = sp.me()["id"]
    
    # Create the playlist shell
    playlist = sp.user_playlist_create(
        user=user_id,
        name=f"AI: {user_prompt[:30]}...",
        public=True,
        description="Generated by my custom Python AI Music App."
    )
    
    # Inject the track IDs into the new playlist
    sp.playlist_add_items(playlist_id=playlist["id"], items=track_uris)
    print(f"🎉 Success! Your playlist is ready. Open it here: {playlist['external_urls']['spotify']}")
else:
    print("\n😕 No tracks were found on Spotify, so no playlist was created.")

